// 深度学习考试题库 - 300题
// type: choice(选择) / fill(填空) / truefalse(判断) / short(简答)
const questionBank = [
// ===== 神经网络基础 1-30 =====
{id:1,cat:"神经网络基础",type:"choice",q:"线性回归和逻辑回归的核心区别？",opts:["A. 线性回归用MSE损失输出连续值，逻辑回归用交叉熵输出0~1概率","B. 没有区别","C. 逻辑回归不能用梯度下降","D. 线性回归只能一维"],ans:"A",exp:"线性回归输出连续实数值用MSE；逻辑回归输出0~1概率用交叉熵(BCEWithLogitsLoss)。"},
{id:2,cat:"神经网络基础",type:"choice",q:"nn.Linear(13, 1)含bias参数量？",opts:["A. 13","B. 14","C. 26","D. 1"],ans:"B",exp:"13×1 + 1(bias) = 14。"},
{id:3,cat:"神经网络基础",type:"choice",q:"回归任务为什么输出层不加激活函数？",opts:["A. 加了会报错","B. 需要输出任意实数值，激活函数会限制范围","C. 回归不需要损失函数","D. 激活函数只用于分类"],ans:"B",exp:"加Sigmoid限制(0,1)，加ReLU限制[0,∞)，都无法预测负值。"},
{id:4,cat:"神经网络基础",type:"choice",q:"二分类和多分类在模型设计上的唯一区别？",opts:["A. 隐藏层数不同","B. 输出层神经元数和激活函数不同","C. 损失函数相同","D. 优化器不同"],ans:"B",exp:"二分类：1个神经元+Sigmoid；多分类：C个神经元+Softmax。"},
{id:5,cat:"神经网络基础",type:"truefalse",q:"PyTorch的CrossEntropyLoss需要手动将整数标签转为one-hot。",ans:"false",exp:"不需要，CrossEntropyLoss直接接受整数标签，内部自动处理。"},
{id:6,cat:"神经网络基础",type:"choice",q:"optimizer.zero_grad()忘记写会怎样？",opts:["A. 报错","B. 梯度累加到之前batch的梯度上","C. 没有影响","D. 自动清空"],ans:"B",exp:"第2个batch梯度会累加到第1个的梯度上。"},
{id:7,cat:"神经网络基础",type:"choice",q:"前向传播和反向传播哪个耗时更多？",opts:["A. 前向传播","B. 反向传播（约2~3倍）","C. 一样多","D. 取决于模型"],ans:"B",exp:"反向传播需计算所有梯度并存储，约为前向的2~3倍。"},
{id:8,cat:"神经网络基础",type:"choice",q:"10000样本batch=128，一个epoch几次参数更新？",opts:["A. 100","B. 78","C. 79","D. 128"],ans:"C",exp:"ceil(10000/128) = 79次。"},
{id:9,cat:"神经网络基础",type:"choice",q:"DNN的'深度'指什么？",opts:["A. 输入维度","B. 隐藏层的层数","C. 输出维度","D. 参数量"],ans:"B",exp:"深度=隐藏层数。"},
{id:10,cat:"神经网络基础",type:"choice",q:"DNN和MLP有什么区别？",opts:["A. DNN更复杂","B. MLP只能回归","C. 本质上是一回事","D. MLP不反向传播"],ans:"C",exp:"MLP是传统叫法，DNN强调深度，语境下通常等价。"},
{id:11,cat:"神经网络基础",type:"choice",q:"万能近似定理说什么？",opts:["A. 任何网络能拟合任何函数","B. 足够宽的单隐藏层网络可逼近任意连续函数","C. 深层一定比浅层好","D. 参数越多越好"],ans:"B",exp:"理论上一个足够宽的单隐藏层MLP可逼近任意连续函数，但'足够宽'可能不实际。"},
{id:12,cat:"神经网络基础",type:"choice",q:"实际中深而窄比浅而宽更高效的原因？",opts:["A. 参数更少且层次化特征更强","B. 浅网络无法训练","C. 宽网络不能反向传播","D. 没区别"],ans:"A",exp:"深层用更少参数学到层次化特征（边缘→形状→语义）。"},
{id:13,cat:"神经网络基础",type:"choice",q:"逻辑回归用什么损失函数？",opts:["A. MSE","B. CrossEntropyLoss","C. BCEWithLogitsLoss","D. NLLLoss"],ans:"C",exp:"逻辑回归=二分类，用BCEWithLogitsLoss（内部含Sigmoid）。"},
{id:14,cat:"神经网络基础",type:"choice",q:"多分类输出层用什么激活函数？",opts:["A. Sigmoid","B. ReLU","C. Softmax","D. Tanh"],ans:"C",exp:"Softmax将输出转为概率分布（和为1）。"},
{id:15,cat:"神经网络基础",type:"choice",q:"没有偏置b会怎样？",opts:["A. 更好","B. 所有x=0时输出必为0，模型缺乏灵活性","C. 无法训练","D. 梯度消失"],ans:"B",exp:"没有bias模型无法在无输入时产生非零输出。"},
{id:16,cat:"神经网络基础",type:"truefalse",q:"nn.Linear也叫'全连接层'，因为上一层每个神经元都与下一层每个神经元相连。",ans:"true",exp:"全连接=每个输入连到每个输出。"},
{id:17,cat:"神经网络基础",type:"choice",q:"model.train()影响哪些层？",opts:["A. 所有层","B. Dropout和BatchNorm","C. 只影响Linear","D. 没影响"],ans:"B",exp:"train()让Dropout生效、BN用batch统计量。"},
{id:18,cat:"神经网络基础",type:"choice",q:"torch.no_grad()的作用？",opts:["A. 加速训练","B. 不构建计算图，节省显存","C. 清空梯度","D. 冻结参数"],ans:"B",exp:"不存储中间变量用于反向传播，节省显存。"},
{id:19,cat:"神经网络基础",type:"choice",q:"什么是Epoch？",opts:["A. 一次前向","B. 一次参数更新","C. 所有训练数据被完整使用一遍","D. 一个batch"],ans:"C",exp:"Epoch=所有数据用一遍=N个Iteration。"},
{id:20,cat:"神经网络基础",type:"choice",q:"训练循环正确顺序？",opts:["A. forward→backward→zero_grad→step","B. zero_grad→forward→loss→backward→step","C. backward→forward→step→zero_grad","D. step→zero_grad→forward→backward"],ans:"B",exp:"①清空梯度 ②前向传播 ③计算损失 ④反向传播 ⑤更新参数。"},
{id:21,cat:"神经网络基础",type:"choice",q:"3层DNN: Linear(784→256)→Linear(256→128)→Linear(128→10)含bias总参数量？",opts:["A. 235,146","B. 200,000","C. 300,000","D. 235,000"],ans:"A",exp:"200,960+32,896+1,290=235,146。"},
{id:22,cat:"神经网络基础",type:"choice",q:"权重W的作用？",opts:["A. 平移激活函数","B. 控制每个输入对输出的影响程度","C. 引入非线性","D. 归一化"],ans:"B",exp:"W控制输入特征重要性。"},
{id:23,cat:"神经网络基础",type:"choice",q:"回归用什么损失函数？",opts:["A. CrossEntropyLoss","B. BCEWithLogitsLoss","C. MSE","D. NLLLoss"],ans:"C",exp:"回归输出连续值用MSE。"},
{id:24,cat:"神经网络基础",type:"choice",q:"二分类输出层用什么激活？",opts:["A. Softmax","B. ReLU","C. Sigmoid","D. Tanh"],ans:"C",exp:"二分类输出0~1概率用Sigmoid。"},
{id:25,cat:"神经网络基础",type:"choice",q:"回归输出层用什么激活？",opts:["A. Sigmoid","B. Softmax","C. ReLU","D. 无激活(Linear)"],ans:"D",exp:"回归需输出任意实数值，不加激活。"},
{id:26,cat:"神经网络基础",type:"choice",q:"batch_size从64改为128，一个epoch时间怎么变？",opts:["A. 一定变慢","B. 一定变快","C. 单次iteration变慢但次数减少，总时间不一定大幅变化","D. 不变"],ans:"C",exp:"GPU充足时大batch利用率更高可能更快。"},
{id:27,cat:"神经网络基础",type:"choice",q:"model.eval()时BatchNorm用什么统计量？",opts:["A. 当前batch","B. 训练期间累积的全局统计量","C. 随机","D. 不用"],ans:"B",exp:"eval模式用训练时累积的全局均值和方差。"},
{id:28,cat:"神经网络基础",type:"truefalse",q:"前向传播是输入→网络→输出，反向传播是损失→梯度→链式法则回传。",ans:"true",exp:"前向=数据从输入到输出，反向=梯度从输出损失回传到权重。"},
{id:29,cat:"神经网络基础",type:"choice",q:"DNN处理224x224x3图像展平后维度？",opts:["A. 50176","B. 150528","C. 672","D. 448"],ans:"B",exp:"224×224×3=150,528维。"},
{id:30,cat:"神经网络基础",type:"choice",q:"logits是什么？",opts:["A. 概率值","B. 模型最后一层的原始输出（未经Softmax）","C. 损失值","D. 梯度"],ans:"B",exp:"logits是神经网络原始输出，CrossEntropyLoss对其做LogSoftmax。"},
// ===== CNN 31-70 =====
{id:31,cat:"CNN",type:"choice",q:"卷积输出尺寸公式？",opts:["A. (H+K-2P)/S","B. ⌊(H-K+2P)/S⌋+1","C. H-K+1","D. H/S"],ans:"B",exp:"H_out = ⌊(H_in - K + 2P)/S⌋ + 1。"},
{id:32,cat:"CNN",type:"choice",q:"卷积层参数量公式？",opts:["A. in×out","B. in×out×K²+out(bias)","C. in+out+K","D. in×K²"],ans:"B",exp:"Params = C_in×C_out×K² + C_out。"},
{id:33,cat:"CNN",type:"choice",q:"输入32×32×3, Conv2d(3,64,3,padding=1,stride=1)输出尺寸？",opts:["A. (64,30,30)","B. (64,32,32)","C. (64,28,28)","D. (32,32,32)"],ans:"B",exp:"padding=1保持尺寸不变。"},
{id:34,cat:"CNN",type:"choice",q:"输入224×224, Conv2d(3,64,7,stride=2,padding=3)输出？",opts:["A. 112×112","B. 111×111","C. 114×114","D. 224×224"],ans:"A",exp:"(224-7+6)/2+1=112。"},
{id:35,cat:"CNN",type:"choice",q:"为什么常用3×3卷积而少用7×7？",opts:["A. 更快","B. 2层3×3=5×5感受野但参数更少且多一层ReLU非线性","C. 7×7不能提取特征","D. padding更容易"],ans:"B",exp:"3层3×3感受野=7×7，参数$27C^2$；1层7×7需要$49C^2$，参数近2倍。"},
{id:36,cat:"CNN",type:"choice",q:"same padding是什么意思？",opts:["A. 所有卷积相同padding","B. 输出尺寸=输入尺寸","C. padding=stride","D. 不补零"],ans:"B",exp:"K=3→P=1, K=5→P=2, K=7→P=3。"},
{id:37,cat:"CNN",type:"choice",q:"K=3时same padding应设？",opts:["A. 0","B. 1","C. 2","D. 3"],ans:"B",exp:"P=(K-1)/2=1。"},
{id:38,cat:"CNN",type:"choice",q:"MaxPool和AvgPool的区别？",opts:["A. MaxPool有参数","B. MaxPool取最大值保留最显著特征；AvgPool取平均保留整体信息","C. 没区别","D. MaxPool只能用于CNN"],ans:"B",exp:"MaxPool保留最显著特征，AvgPool更平滑。"},
{id:39,cat:"CNN",type:"truefalse",q:"池化层没有可学习参数。",ans:"true",exp:"池化是固定数学运算（取最大/取平均），不需要学习。"},
{id:40,cat:"CNN",type:"choice",q:"Global Average Pooling的优势？",opts:["A. 更快","B. 零参数且不依赖输入尺寸","C. 精度更高","D. 替代卷积"],ans:"B",exp:"GAP无参数+输出维度=通道数(固定)，可接受任意大小图像。"},
{id:41,cat:"CNN",type:"choice",q:"CNN标准块的正确顺序？",opts:["A. ReLU→Conv→BN→Pool","B. Conv→BN→ReLU→Pool","C. BN→Conv→ReLU","D. Conv→ReLU→BN"],ans:"B",exp:"Conv(提特征)→BN(归一化)→ReLU(非线性)→Pool(下采样)。"},
{id:42,cat:"CNN",type:"choice",q:"CNN通道数变化规律？",opts:["A. 逐层减半","B. 不变","C. 逐层翻倍，空间尺寸逐层减半","D. 随机"],ans:"C",exp:"通道翻倍提取更多特征，空间减半关注全局语义。"},
{id:43,cat:"CNN",type:"choice",q:"经过3次MaxPool2d(2,2)后224变为？",opts:["A. 28","B. 56","C. 112","D. 14"],ans:"A",exp:"224→112→56→28。"},
{id:44,cat:"CNN",type:"choice",q:"BN应放在Conv和ReLU的什么位置？",opts:["A. BN→Conv→ReLU","B. Conv→ReLU→BN","C. Conv→BN→ReLU","D. 随便"],ans:"C",exp:"Conv→BN→ReLU是标准顺序。"},
{id:45,cat:"CNN",type:"choice",q:"ResNet的核心创新？",opts:["A. 大卷积核","B. 跳跃连接 H(x)=F(x)+x","C. 增加宽度","D. 更多FC层"],ans:"B",exp:"跳跃连接让梯度可以直通浅层。"},
{id:46,cat:"CNN",type:"choice",q:"残差连接为什么缓解梯度消失？",opts:["A. 增加参数","B. ∂H/∂x=∂F/∂x+1，+1保证梯度至少为1","C. 用更大lr","D. 减少深度"],ans:"B",exp:"+1提供梯度高速通道。"},
{id:47,cat:"CNN",type:"choice",q:"Bottleneck结构是什么？",opts:["A. 3×3→5×5→3×3","B. 1×1降维→3×3→1×1升维","C. 7×7→3×3→7×7","D. 只有1×1"],ans:"B",exp:"参数从256×256×9=590K降到69K，节省1/8。"},
{id:48,cat:"CNN",type:"choice",q:"ResNet18用什么块？",opts:["A. Bottleneck","B. BasicBlock(2个3×3)","C. Inception","D. FC块"],ans:"B",exp:"ResNet18用BasicBlock，ResNet50用Bottleneck。"},
{id:49,cat:"CNN",type:"choice",q:"VGG的核心哲学？",opts:["A. 大卷积核","B. 全部使用3×3小核堆叠","C. 只用FC","D. 残差连接"],ans:"B",exp:"小核堆叠：参数更少、非线性更多。"},
{id:50,cat:"CNN",type:"choice",q:"VGG16有几层？",opts:["A. 19","B. 16（13Conv+3FC）","C. 13","D. 34"],ans:"B",exp:"13层卷积+3层全连接=16。"},
{id:51,cat:"CNN",type:"choice",q:"迁移学习两种策略？",opts:["A. 预训练和微调","B. 特征提取器(冻结)和微调(小lr)","C. 增强和正则","D. 剪枝和量化"],ans:"B",exp:"小数据用特征提取器(冻结)，中等数据用微调(小lr)。"},
{id:52,cat:"CNN",type:"choice",q:"1×1卷积的两大用途？",opts:["A. 增大感受野和提取纹理","B. 改变通道数+跨通道信息融合","C. 替代FC和Pool","D. 增强和正则"],ans:"B",exp:"1×1在通道维度做全连接。"},
{id:53,cat:"CNN",type:"choice",q:"Conv2d(256,64,1)参数量？",opts:["A. 16384","B. 16448","C. 262144","D. 256"],ans:"B",exp:"256×64×1+64=16448。"},
{id:54,cat:"CNN",type:"choice",q:"空洞卷积(dilation=2,K=3)等效感受野？",opts:["A. 3×3","B. 5×5","C. 7×7","D. 9×9"],ans:"B",exp:"K_eff=K+(K-1)(d-1)=3+2=5。"},
{id:55,cat:"CNN",type:"choice",q:"深度可分离卷积分哪两步？",opts:["A. 1×1和池化","B. Depthwise(逐通道)+Pointwise(1×1融合)","C. 空洞和标准","D. 上采样和下采样"],ans:"B",exp:"参数量约为标准卷积的1/8。"},
{id:56,cat:"CNN",type:"choice",q:"MobileNet用什么卷积？",opts:["A. 标准3×3","B. 7×7","C. 深度可分离卷积","D. 空洞卷积"],ans:"C",exp:"适合移动端/嵌入式。"},
{id:57,cat:"CNN",type:"choice",q:"CNN中Dropout常用在哪？",opts:["A. 卷积层","B. 池化层","C. FC(全连接)层","D. 输入层"],ans:"C",exp:"Conv参数少有天然正则化，FC参数大过拟合风险高。"},
{id:58,cat:"CNN",type:"truefalse",q:"数据增强在训练和测试时都需要。",ans:"false",exp:"只有训练时需要，测试时用原始图像。"},
{id:59,cat:"CNN",type:"choice",q:"Mixup是什么？",opts:["A. 随机翻转","B. 两张图像按比例混合（输入+标签都混合）","C. 裁剪拼接","D. 随机擦除"],ans:"B",exp:"x_mix=λ·x_a+(1-λ)·x_b，标签也按比例混合。"},
{id:60,cat:"CNN",type:"choice",q:"2层3×3卷积感受野？",opts:["A. 3×3","B. 5×5","C. 7×7","D. 9×9"],ans:"B",exp:"每层贡献2个额外像素：3+2=5。"},
{id:61,cat:"CNN",type:"choice",q:"3层3×3卷积感受野？",opts:["A. 5×5","B. 7×7","C. 9×9","D. 3×3"],ans:"B",exp:"3+2+2=7。"},
{id:62,cat:"CNN",type:"choice",q:"Conv2d(3,64,3)不含bias参数量？",opts:["A. 1728","B. 1792","C. 576","D. 64"],ans:"A",exp:"3×3×3×64=1728。"},
{id:63,cat:"CNN",type:"choice",q:"Conv2d(3,64,3)含bias参数量？",opts:["A. 1728","B. 1792","C. 1856","D. 384"],ans:"B",exp:"1728+64=1792。"},
{id:64,cat:"CNN",type:"choice",q:"CNN通过什么解决DNN处理图像的参数爆炸？",opts:["A. 增加层数","B. 局部连接+权重共享","C. 减小输入","D. 大batch"],ans:"B",exp:"卷积核只连局部+共享权重，大幅减少参数。"},
{id:65,cat:"CNN",type:"choice",q:"什么情况下迁移学习效果不好？",opts:["A. 数据量大","B. 预训练数据和目标数据差异极大（如医学影像）","C. 用微调","D. 用小lr"],ans:"B",exp:"预训练特征在差异极大的领域不适用。"},
{id:66,cat:"CNN",type:"choice",q:"第一层Conv通常用什么stride？",opts:["A. 1","B. stride=2替代Pool层来下采样","C. 4","D. 0"],ans:"B",exp:"可学习的下采样更灵活。"},
{id:67,cat:"CNN",type:"choice",q:"竖直翻转适合什么任务？",opts:["A. 自然场景","B. 卫星图/显微镜图（无上下概念）","C. 人脸识别","D. 自动驾驶"],ans:"B",exp:"没有固定上下方向的任务适合竖直翻转。"},
{id:68,cat:"CNN",type:"choice",q:"空洞卷积的作用？",opts:["A. 减小参数","B. 不增加参数增大感受野","C. 提高分辨率","D. 加速训练"],ans:"B",exp:"像素间插入空洞，增大实际覆盖区域。"},
{id:69,cat:"CNN",type:"choice",q:"MaxPool2d(2,2)将特征图尺寸？",opts:["A. 不变","B. 减半","C. 变1/4","D. 翻倍"],ans:"B",exp:"每个维度减半。"},
{id:70,cat:"CNN",type:"choice",q:"CNN卷积核在浅层学到什么？",opts:["A. 完整物体","B. 语义特征","C. 边缘、颜色梯度","D. 物体部件"],ans:"C",exp:"浅层→边缘/颜色；中层→纹理/形状；深层→语义。"},
// ===== RNN/LSTM/GRU 71-100 =====
{id:71,cat:"RNN/LSTM",type:"choice",q:"SimpleRNN核心公式？",opts:["A. h_t=ReLU(Wx_t+b)","B. h_t=tanh(Wx_t+Uh_{t-1}+b)","C. h_t=sigmoid(Wx_t)","D. h_t=Wx_t+b"],ans:"B",exp:"包含输入和上一时刻隐藏状态。"},
{id:72,cat:"RNN/LSTM",type:"truefalse",q:"RNN权重在所有时间步共享，无论序列多长参数量不变。",ans:"true",exp:"W、U、b在所有时间步复用。"},
{id:73,cat:"RNN/LSTM",type:"choice",q:"序列长度从10变100，RNN参数量？",opts:["A. 增10倍","B. 不变","C. 增100倍","D. 减少"],ans:"B",exp:"权重共享，与序列长度无关。"},
{id:74,cat:"RNN/LSTM",type:"choice",q:"SimpleRNN为什么用Tanh不用ReLU？",opts:["A. Tanh更快","B. ReLU导致隐藏状态无限增长→梯度爆炸","C. Tanh是唯一激活","D. ReLU不能用于RNN"],ans:"B",exp:"ReLU只输出非负值→状态指数增长→梯度爆炸。"},
{id:75,cat:"RNN/LSTM",type:"choice",q:"BPTT是什么？",opts:["A. 一种优化器","B. 通过时间反向传播","C. 激活函数","D. BN"],ans:"B",exp:"Backpropagation Through Time。"},
{id:76,cat:"RNN/LSTM",type:"choice",q:"RNN梯度消失的数学原因？",opts:["A. 参数太多","B. tanh'和U连乘，小于1连乘趋近0","C. lr太小","D. batch太大"],ans:"B",exp:"每步乘tanh'(≤1)和U，T步连乘→0。"},
{id:77,cat:"RNN/LSTM",type:"choice",q:"loss突然变NaN最可能原因？",opts:["A. 梯度消失","B. 梯度爆炸→参数溢出","C. lr太小","D. 数据少"],ans:"B",exp:"梯度指数增长→参数溢出→NaN。"},
{id:78,cat:"RNN/LSTM",type:"choice",q:"LSTM引入什么解决梯度消失？",opts:["A. 更多层","B. 细胞状态c_t，更新接近线性","C. 更大隐藏层","D. ReLU"],ans:"B",exp:"c_t=f_t⊙c_{t-1}+i_t⊙c̃_t，∂c_t/∂c_{t-1}=f_t。"},
{id:79,cat:"RNN/LSTM",type:"choice",q:"LSTM有几个门？",opts:["A. 1","B. 2","C. 3（遗忘、输入、输出）","D. 4"],ans:"C",exp:"三个门+一个候选记忆。"},
{id:80,cat:"RNN/LSTM",type:"choice",q:"LSTM三个门用什么激活函数？",opts:["A. ReLU","B. Tanh","C. Sigmoid（输出0~1代表门开闭）","D. Softmax"],ans:"C",exp:"Sigmoid输出(0,1)：0=全关，1=全开。"},
{id:81,cat:"RNN/LSTM",type:"choice",q:"LSTM候选记忆c̃_t用什么激活？",opts:["A. Sigmoid","B. Tanh","C. ReLU","D. Softmax"],ans:"B",exp:"输出(-1,1)含正负信息。"},
{id:82,cat:"RNN/LSTM",type:"choice",q:"LSTM共几个参数矩阵？",opts:["A. 4","B. 8","C. 12","D. 16"],ans:"C",exp:"4组(W,U,b)×{遗忘,输入,候选,输出}=12。"},
{id:83,cat:"RNN/LSTM",type:"choice",q:"LSTM中c_t和h_t的区别？",opts:["A. 相同","B. c_t是长期记忆(内部)，h_t是短期输出(对外)","C. h_t更重要","D. c_t只训练用"],ans:"B",exp:"c_t=长期记忆(梯度无损传播)，h_t=c_t经输出门过滤后的发言。"},
{id:84,cat:"RNN/LSTM",type:"choice",q:"遗忘门永远=1，输入门永远=0，LSTM退化成？",opts:["A. 普通RNN","B. 序列累加器(c_t=c_{t-1})，无法遗忘","C. 随机生成器","D. 恒等映射"],ans:"B",exp:"c_t=1·c_{t-1}+0·c̃_t=c_{t-1}，永远记住。"},
{id:85,cat:"RNN/LSTM",type:"choice",q:"num_layers=2和bidirectional=True的区别？",opts:["A. 没区别","B. num_layers=2纵向堆叠(参数翻倍)；bidirectional正反各一层(输出翻倍)","C. 都只增参数","D. bidirectional不影响输出"],ans:"B",exp:"num_layers纵向堆叠深度；bidirectional增加反向LSTM。"},
{id:86,cat:"RNN/LSTM",type:"choice",q:"GRU有几个门？",opts:["A. 3","B. 2（更新门+重置门）","C. 1","D. 4"],ans:"B",exp:"更新门z_t控制新旧混合，重置门r_t控制遗忘。"},
{id:87,cat:"RNN/LSTM",type:"truefalse",q:"GRU没有独立细胞状态，h_t同时扮演LSTM中c_t和h_t角色。",ans:"true",exp:"GRU将c_t和h_t合并。"},
{id:88,cat:"RNN/LSTM",type:"choice",q:"GRU参数量是LSTM的？",opts:["A. 1/2","B. 3/4","C. 相同","D. 2倍"],ans:"B",exp:"9个矩阵 vs 12个。"},
{id:89,cat:"RNN/LSTM",type:"choice",q:"什么时候选GRU不选LSTM？",opts:["A. 大数据集","B. 小数据/追求速度","C. 精细控制","D. 长距离依赖"],ans:"B",exp:"参数少计算快。"},
{id:90,cat:"RNN/LSTM",type:"choice",q:"Teacher Forcing是什么？",opts:["A. 强制学习","B. 训练时用真实标签作为每步输入","C. 预训练","D. 增加深度"],ans:"B",exp:"训练更稳定，但带来Exposure Bias。"},
{id:91,cat:"RNN/LSTM",type:"choice",q:"Exposure Bias是什么？",opts:["A. 过拟合","B. 训练(真实前文)和推理(模型预测)条件不一致导致误差累积","C. 梯度爆炸","D. 数据增强"],ans:"B",exp:"训练见完美输入，推理见有错预测。"},
{id:92,cat:"RNN/LSTM",type:"choice",q:"梯度裁剪代码？",opts:["A. optimizer.clip_norm(5)","B. torch.nn.utils.clip_grad_norm_(params, max_norm=5.0)","C. model.clip_grad(5)","D. loss.clip(5)"],ans:"B",exp:"将梯度范数限制在max_norm以内。"},
{id:93,cat:"RNN/LSTM",type:"choice",q:"LSTM反向传播时∂c_t/∂c_{t-1}等于？",opts:["A. U矩阵","B. f_t（遗忘门值）","C. tanh'(c_t)","D. 0"],ans:"B",exp:"元素级乘法，非矩阵乘法。"},
{id:94,cat:"RNN/LSTM",type:"choice",q:"当f_t≈1时梯度？",opts:["A. 消失","B. 爆炸","C. 几乎无损传播","D. 不变"],ans:"C",exp:"梯度几乎无损跨时间步传播。"},
{id:95,cat:"RNN/LSTM",type:"choice",q:"BiLSTM输出维度是单向几倍？",opts:["A. 1","B. 2（正反拼接）","C. 4","D. 不变"],ans:"B",exp:"正向+反向拼接→2倍。"},
{id:96,cat:"RNN/LSTM",type:"choice",q:"batch_first=True是什么意思？",opts:["A. Batch优先","B. 输入(B,T,D)而非(T,B,D)","C. Batch只能1","D. 不影响"],ans:"B",exp:"batch_first=True：(batch,seq,features)。"},
{id:97,cat:"RNN/LSTM",type:"choice",q:"h0形状(num_layers=2, batch=B, hidden=128)？",opts:["A. (B,128)","B. (2,B,128)","C. (B,2,128)","D. (128,B)"],ans:"B",exp:"(num_layers, batch, hidden_dim)。"},
{id:98,cat:"RNN/LSTM",type:"choice",q:"单层单向LSTM(in=128,hidden=256)不含bias参数量？",opts:["A. 98304","B. 393216","C. 196608","D. 131072"],ans:"B",exp:"4×(128×256+256×256)=4×98304=393216。"},
{id:99,cat:"RNN/LSTM",type:"choice",q:"Scheduled Sampling是什么？",opts:["A. 定时保存","B. 逐步增加用自身预测替代真实标签的概率","C. 调lr","D. 采样数据"],ans:"B",exp:"缓解Exposure Bias。"},
{id:100,cat:"RNN/LSTM",type:"choice",q:"LSTM比GRU更适合？",opts:["A. 小数据","B. 大数据/需要精细记忆控制","C. 追求速度","D. 简单任务"],ans:"B",exp:"三扇门提供更精细控制。"},
// ===== Transformer 101-140 =====
{id:101,cat:"Transformer",type:"choice",q:"Self-Attention核心公式？",opts:["A. softmax(QK^T)V","B. softmax(QK^T/√d_k)V","C. QK^TV/√d_k","D. softmax(Q+K+V)"],ans:"B",exp:"除以√d_k做缩放防止饱和。"},
{id:102,cat:"Transformer",type:"choice",q:"Q、K、V分别代表？",opts:["A. 输入/输出/权重","B. 查询(找什么)/键(有什么)/值(实际内容)","C. 特征/标签/预测","D. 编码/解码/注意"],ans:"B",exp:"Q=Query, K=Key, V=Value。"},
{id:103,cat:"Transformer",type:"choice",q:"除以√d_k的目的？",opts:["A. 增大注意力","B. 防止点积过大导致Softmax梯度消失","C. 减小计算量","D. 增加复杂度"],ans:"B",exp:"QK^T方差随d_k线性增长。"},
{id:104,cat:"Transformer",type:"choice",q:"Self-Attention复杂度？",opts:["A. O(L·d)","B. O(L²·d)","C. O(L³)","D. O(d²)"],ans:"B",exp:"QK^T产生L×L矩阵。"},
{id:105,cat:"Transformer",type:"choice",q:"Self-Attention'置换不变'是什么意思？",opts:["A. 参数不更新","B. 打乱输入顺序输出也跟着打乱→无法感知词序","C. 权重固定","D. 不需训练"],ans:"B",exp:"→需要位置编码解决。"},
{id:106,cat:"Transformer",type:"choice",q:"Self-Attention和Cross-Attention的区别？",opts:["A. 计算量","B. Q/K/V来源：Self来自同一输入；Cross的Q来自Decoder、KV来自Encoder","C. 没区别","D. Self只训练用"],ans:"B",exp:"Cross-Attention连接编码器和解码器。"},
{id:107,cat:"Transformer",type:"choice",q:"Multi-Head中d_k=？",opts:["A. d_model","B. d_model/num_heads","C. d_model×num_heads","D. 64"],ans:"B",exp:"保证拼接后总维=d_model。"},
{id:108,cat:"Transformer",type:"choice",q:"d_model=256, num_heads=4, 每个头d_k？",opts:["A. 256","B. 64","C. 128","D. 32"],ans:"B",exp:"256/4=64。"},
{id:109,cat:"Transformer",type:"choice",q:"为什么需要输出投影W_o？",opts:["A. 减小维度","B. 跨头信息交互和重新组合","C. 加速","D. 正则化"],ans:"B",exp:"没有W_o各头只是简单拼接，缺乏综合。"},
{id:110,cat:"Transformer",type:"choice",q:"Encoder Block几个子层？",opts:["A. 1","B. 2（Self-Attn+FFN）","C. 3","D. 4"],ans:"B",exp:"每个子层都有残差连接+归一化。"},
{id:111,cat:"Transformer",type:"choice",q:"Decoder Block几个子层？",opts:["A. 1","B. 2","C. 3（Masked Self-Attn+Cross-Attn+FFN）","D. 4"],ans:"C",exp:"比Encoder多一个Cross-Attention。"},
{id:112,cat:"Transformer",type:"choice",q:"Pre-LN公式？",opts:["A. LN(x+Sublayer(x))","B. x+Sublayer(LN(x))","C. LN(x)+LN(Sublayer(x))","D. x×Sublayer(LN(x))"],ans:"B",exp:"LN在残差之前，梯度可直通。"},
{id:113,cat:"Transformer",type:"choice",q:"Post-LN公式？",opts:["A. x+Sublayer(LN(x))","B. LN(x+Sublayer(x))","C. LN(x)+Sublayer(x)","D. x·LN(Sublayer(x))"],ans:"B",exp:"LN在残差之后。"},
{id:114,cat:"Transformer",type:"choice",q:"Pre-LN为什么更稳定？",opts:["A. 参数少","B. 梯度可通过残差直通，不经LN衰减","C. lr更大","D. 不需归一化"],ans:"B",exp:"残差连接提供+1梯度通道。"},
{id:115,cat:"Transformer",type:"choice",q:"FFN中间维度通常是d_model的？",opts:["A. 2倍","B. 4倍","C. 8倍","D. 相同"],ans:"B",exp:"d_model→4d_model→d_model增加非线性容量。"},
{id:116,cat:"Transformer",type:"choice",q:"去掉FFN会怎样？",opts:["A. 没影响","B. 退化为近似线性映射，失去复杂模式学习能力","C. 更快","D. 更好"],ans:"B",exp:"Attention本质是加权求和(线性)，FFN提供非线性。"},
{id:117,cat:"Transformer",type:"choice",q:"正弦位置编码公式？",opts:["A. PE=pos/d","B. PE(pos,2i)=sin(pos/10000^(2i/d))","C. PE=pos×i","D. PE=sin(pos)"],ans:"B",exp:"偶数位sin，奇数位cos。"},
{id:118,cat:"Transformer",type:"choice",q:"可学习位置编码的缺点？",opts:["A. 精度低","B. 超过训练长度无法外推","C. 参数太大","D. 训练慢"],ans:"B",exp:"只训练了max_len以内的位置。"},
{id:119,cat:"Transformer",type:"choice",q:"正弦位置编码的优点？",opts:["A. 精度高","B. 可外推任意长度","C. 参数少","D. 训练快"],ans:"B",exp:"确定性函数，输入任意pos都能计算。"},
{id:120,cat:"Transformer",type:"choice",q:"Causal Mask形状？",opts:["A. 全1","B. 下三角矩阵","C. 上三角","D. 对角"],ans:"B",exp:"位置i只看≤i的位置。"},
{id:121,cat:"Transformer",type:"choice",q:"Causal Mask在哪里设-inf？",opts:["A. 下三角","B. 上三角（j>i即'未来'）","C. 对角线","D. 全部"],ans:"B",exp:"-inf在softmax后变0，防止看未来。"},
{id:122,cat:"Transformer",type:"choice",q:"自回归数学定义？",opts:["A. P(x)=ΣP(x_t)","B. P(x)=ΠP(x_t|x_1,...,x_{t-1})","C. P(x)=P(x_1)×P(x_2)","D. P(x)=max(P(x_t))"],ans:"B",exp:"每个token在前缀条件下的概率连乘。"},
{id:123,cat:"Transformer",type:"choice",q:"Greedy解码特点？",opts:["A. 保留多条路径","B. 每步取最大概率，快但单调","C. 随机采样","D. 全局搜索"],ans:"B",exp:"速度快但缺乏多样性。"},
{id:124,cat:"Transformer",type:"choice",q:"Beam Search特点？",opts:["A. 只留一条路径","B. 每步保留top-K路径，适合翻译","C. 完全随机","D. 只用一次"],ans:"B",exp:"比Greedy好，适合精确性要求高的任务。"},
{id:125,cat:"Transformer",type:"choice",q:"Temperature τ>1会？",opts:["A. 更尖锐","B. 更平滑，生成更多样","C. 不变","D. 不收敛"],ans:"B",exp:"token间概率差距缩小。"},
{id:126,cat:"Transformer",type:"choice",q:"τ<1会？",opts:["A. 更尖锐，生成更确定","B. 更平滑","C. 随机性增大","D. 崩溃"],ans:"A",exp:"概率集中在高分token。"},
{id:127,cat:"Transformer",type:"choice",q:"BERT是什么架构？",opts:["A. Decoder-Only","B. Encoder-Only","C. Encoder-Decoder","D. RNN"],ans:"B",exp:"双向Self-Attn+Masked Language Model。"},
{id:128,cat:"Transformer",type:"choice",q:"GPT是什么架构？",opts:["A. Encoder-Only","B. Decoder-Only","C. Encoder-Decoder","D. CNN"],ans:"B",exp:"单向Causal Self-Attn+Next Token Prediction。"},
{id:129,cat:"Transformer",type:"choice",q:"T5是什么架构？",opts:["A. Encoder-Only","B. Decoder-Only","C. Encoder-Decoder","D. RNN"],ans:"C",exp:"Encoder双向编码+Decoder自回归+Cross-Attn。"},
{id:130,cat:"Transformer",type:"choice",q:"GPT训练目标？",opts:["A. 完形填空","B. Next Token Prediction","C. 图像分类","D. 对比学习"],ans:"B",exp:"给定前缀预测下一个token。"},
{id:131,cat:"Transformer",type:"choice",q:"BERT训练目标？",opts:["A. Next Token Prediction","B. Masked Language Model(完形填空)","C. 翻译","D. 图像生成"],ans:"B",exp:"随机掩盖15%token预测被掩盖词。"},
{id:132,cat:"Transformer",type:"choice",q:"GPT为什么只有Decoder？",opts:["A. 节省","B. 语言建模天然适合自回归Decoder-Only","C. Encoder没用","D. 历史原因"],ans:"B",exp:"给前缀预测下一个词=自回归。"},
{id:133,cat:"Transformer",type:"choice",q:"KV-Cache缓存什么？",opts:["A. 注意力权重","B. 已生成token的Key和Value","C. 全部参数","D. 梯度"],ans:"B",exp:"避免重复计算历史。"},
{id:134,cat:"Transformer",type:"choice",q:"KV-Cache将复杂度从？降到？",opts:["A. O(L)到O(1)","B. O(t²)到O(t)","C. O(L²)到O(L)","D. O(n)到O(logn)"],ans:"B",exp:"每步只算新token。"},
{id:135,cat:"Transformer",type:"choice",q:"MQA是什么？",opts:["A. 每个头独立KV","B. 所有头共享同一组KV，Q独立","C. 不需Q","D. 只有Query"],ans:"B",exp:"最省显存。"},
{id:136,cat:"Transformer",type:"choice",q:"GQA是什么？",opts:["A. 所有共享KV","B. 头分组，组内共享KV（折中）","C. 每个头独立KV","D. 不需K"],ans:"B",exp:"MQA和MHA的折中。"},
{id:137,cat:"Transformer",type:"truefalse",q:"FlashAttention改变了注意力机制的数学公式。",ans:"false",exp:"没有改变数学公式，只是IO优化(分块+利用SRAM)。"},
{id:138,cat:"Transformer",type:"choice",q:"MoE(混合专家)是什么？",opts:["A. 多模型集成","B. FFN替换为多个专家，每次只激活一部分","C. 多头注意力","D. 多数据集"],ans:"B",exp:"增加容量不增加计算。"},
{id:139,cat:"Transformer",type:"choice",q:"情感分类选什么架构？",opts:["A. Decoder-Only","B. Encoder-Only(BERT)","C. GAN","D. CNN"],ans:"B",exp:"理解任务不需生成，BERT双向注意力看完整上下文。"},
{id:140,cat:"Transformer",type:"choice",q:"GPT能做分类吗？",opts:["A. 完全不行","B. 能，通过Prompt自回归生成答案(In-Context Learning)","C. 只能微调","D. 只能用BERT"],ans:"B",exp:"Prompt方式效果通常比微调BERT差但胜在通用。"},
// ===== 损失函数 141-160 =====
{id:141,cat:"损失函数",type:"choice",q:"MSE适用什么任务？",opts:["A. 分类","B. 回归","C. 聚类","D. 生成"],ans:"B",exp:"MSE用于回归任务。"},
{id:142,cat:"损失函数",type:"choice",q:"CrossEntropyLoss适用？",opts:["A. 回归","B. 多分类","C. 聚类","D. 生成"],ans:"B",exp:"多分类。"},
{id:143,cat:"损失函数",type:"choice",q:"BCEWithLogitsLoss适用？",opts:["A. 多分类","B. 二分类","C. 回归","D. 聚类"],ans:"B",exp:"=Sigmoid+BCELoss。"},
{id:144,cat:"损失函数",type:"choice",q:"CrossEntropyLoss内部包含？",opts:["A. Softmax+MSE","B. LogSoftmax+NLLLoss","C. Sigmoid+BCE","D. Softmax+NLL"],ans:"B",exp:"模型不需要再手动加Softmax。"},
{id:145,cat:"损失函数",type:"choice",q:"双重Softmax的症状？",opts:["A. loss太快","B. loss卡在-log(1/C)不下降","C. 梯度爆炸","D. 过拟合"],ans:"B",exp:"概率趋于均匀分布。"},
{id:146,cat:"损失函数",type:"choice",q:"10分类双重Softmax loss约等于？",opts:["A. 0","B. 1","C. 2.3026","D. 10"],ans:"C",exp:"-log(1/10)≈2.3026。"},
{id:147,cat:"损失函数",type:"choice",q:"回归为什么不能用交叉熵？",opts:["A. 太慢","B. 交叉熵要求概率分布，回归输出连续值","C. 只能二分类","D. 不需要损失函数"],ans:"B",exp:"交叉熵要求输入是概率分布(0~1,和为1)。"},
{id:148,cat:"损失函数",type:"choice",q:"Softmax中为什么要减max？",opts:["A. 加速","B. 防止e^x指数溢出为inf","C. 减小数值","D. 没原因"],ans:"B",exp:"减max后最大值=0，e^0=1不溢出。"},
{id:149,cat:"损失函数",type:"truefalse",q:"F.cross_entropy和F.nll_loss+F.log_softmax结果相等。",ans:"true",exp:"CrossEntropyLoss=LogSoftmax+NLLLoss。"},
{id:150,cat:"损失函数",type:"truefalse",q:"多分类标签是整数时必须手动转one-hot才能用CrossEntropyLoss。",ans:"false",exp:"PyTorch直接接受整数标签。"},
{id:151,cat:"损失函数",type:"choice",q:"MAE和MSE主要区别？",opts:["A. MAE更快","B. MAE对异常值更鲁棒","C. 没区别","D. MSE更准"],ans:"B",exp:"MAE绝对值不受极端值影响。"},
{id:152,cat:"损失函数",type:"choice",q:"NLLLoss需要什么输入？",opts:["A. 原始logits","B. log-probability","C. 原始数据","D. one-hot"],ans:"B",exp:"需先LogSoftmax。"},
{id:153,cat:"损失函数",type:"choice",q:"LogSoftmax+NLLLoss等价于？",opts:["A. MSE","B. CrossEntropyLoss","C. BCELoss","D. MAE"],ans:"B",exp:"数值更稳定。"},
{id:154,cat:"损失函数",type:"choice",q:"二分类用几个输出神经元？",opts:["A. 0","B. 1","C. 2","D. 10"],ans:"B",exp:"1个神经元+Sigmoid。"},
{id:155,cat:"损失函数",type:"choice",q:"Softmax作用？",opts:["A. 正则化","B. 将实数转为概率分布(和为1)","C. 归一化","D. 激活隐藏层"],ans:"B",exp:"指数映射(正数化)+归一化。"},
{id:156,cat:"损失函数",type:"choice",q:"BCEWithLogitsLoss和BCELoss区别？",opts:["A. 没区别","B. 前者内部含Sigmoid，后者需手动","C. 前者更快","D. 后者更稳定"],ans:"B",exp:"前者一步完成，数值更稳定。"},
{id:157,cat:"损失函数",type:"choice",q:"Label Smoothing是什么？",opts:["A. 数据增强","B. 标签从hard变soft防过度自信","C. 梯度裁剪","D. lr衰减"],ans:"B",exp:"[0,0,1,0]→[0.025,0.025,0.925,0.025]。"},
{id:158,cat:"损失函数",type:"truefalse",q:"模型最后一层已做Softmax，传入CrossEntropyLoss是正确做法。",ans:"false",exp:"错误！导致双重Softmax。"},
{id:159,cat:"损失函数",type:"choice",q:"回归输出层用什么激活？",opts:["A. Sigmoid","B. Softmax","C. ReLU","D. 无激活"],ans:"D",exp:"需输出任意实数值。"},
{id:160,cat:"损失函数",type:"choice",q:"多分类输出几个神经元？",opts:["A. 1","B. 2","C. C个(类别数)","D. 10"],ans:"C",exp:"每个类别一个。"},

// ===== 优化器 161-175 =====
{id:161,cat:"优化器",type:"choice",q:"SGD更新公式？",opts:["A. θ+=η·∇L","B. θ-=η·∇L","C. θ=θ×η","D. θ=0"],ans:"B",exp:"沿负梯度方向。"},
{id:162,cat:"优化器",type:"choice",q:"Adam核心特点？",opts:["A. 只用动量","B. 动量+自适应学习率","C. 只自适应","D. 固定lr"],ans:"B",exp:"默认首选。"},
{id:163,cat:"优化器",type:"choice",q:"AdamW和Adam区别？",opts:["A. AdamW更快","B. AdamW解耦Weight Decay","C. 没区别","D. AdamW更慢"],ans:"B",exp:"L2正则直接作用于参数。"},
{id:164,cat:"优化器",type:"choice",q:"Transformer用什么优化器？",opts:["A. SGD","B. Adam","C. AdamW","D. RMSProp"],ans:"C",exp:"Transformer标准优化器。"},
{id:165,cat:"优化器",type:"choice",q:"学习率太大会？",opts:["A. 收敛更快","B. 震荡/发散/NaN","C. 精度更高","D. 没影响"],ans:"B",exp:"步长过大越过最优解。"},
{id:166,cat:"优化器",type:"choice",q:"学习率太小会？",opts:["A. 更快","B. 震荡","C. 收敛太慢/陷入局部最优","D. 梯度爆炸"],ans:"C",exp:"步长过小。"},
{id:167,cat:"优化器",type:"choice",q:"StepLR做什么？",opts:["A. 余弦衰减","B. 每N步lr×gamma","C. 指数增长","D. 不变"],ans:"B",exp:"阶梯式衰减。"},
{id:168,cat:"优化器",type:"choice",q:"CosineAnnealingLR做什么？",opts:["A. 阶梯衰减","B. 余弦曲线平滑衰减","C. 线性增长","D. 随机"],ans:"B",exp:"最常用调度策略。"},
{id:169,cat:"优化器",type:"choice",q:"Warmup的作用？",opts:["A. 预热GPU","B. 训练初期lr从小逐步增大","C. 加速训练","D. 数据预处理"],ans:"B",exp:"避免初期不稳定。"},
{id:170,cat:"优化器",type:"choice",q:"Transformer为什么需要Warmup？",opts:["A. GPU需要","B. 初期梯度方差大，大lr会导致跑偏","C. 数据少","D. 模型大"],ans:"B",exp:"先找到方向再加速。"},
{id:171,cat:"优化器",type:"choice",q:"ReduceLROnPlateau做什么？",opts:["A. 定时衰减","B. 验证指标不降时降低lr","C. 增加lr","D. 固定lr"],ans:"B",exp:"基于验证指标自适应调整。"},
{id:172,cat:"优化器",type:"truefalse",q:"Adam比SGD收敛快，但精心调参后SGD泛化可能更好。",ans:"true",exp:"SGD能找到更平坦的极小值。"},
{id:173,cat:"优化器",type:"choice",q:"Momentum作用？",opts:["A. 正则化","B. 加入惯性加速收敛减少震荡","C. 增加参数","D. 数据增强"],ans:"B",exp:"考虑历史梯度方向。"},
{id:174,cat:"优化器",type:"choice",q:"Weight Decay等价于？",opts:["A. L1","B. L2正则","C. Dropout","D. 数据增强"],ans:"B",exp:"λΣW²限制权重大小。"},
{id:175,cat:"优化器",type:"choice",q:"追求最佳泛化选什么？",opts:["A. Adam","B. SGD+Momentum(精细调参后)","C. AdaGrad","D. RMSProp"],ans:"B",exp:"平坦极小值泛化更好。"},

// ===== 正则化 176-195 =====
{id:176,cat:"正则化",type:"choice",q:"Dropout训练时做什么？",opts:["A. 增加神经元","B. 以概率p随机丢弃(输出置0)","C. 归一化","D. 增加参数"],ans:"B",exp:"测试时全部参与。"},
{id:177,cat:"正则化",type:"choice",q:"Dropout=0.5时训练输出要乘？",opts:["A. 0.5","B. 1/(1-p)=2","C. 不乘","D. p"],ans:"B",exp:"保持训练和测试时期望一致。"},
{id:178,cat:"正则化",type:"choice",q:"Dropout和BatchNorm能同时用吗？",opts:["A. 不能","B. 可以，但可能有方差偏移问题","C. 必须同时","D. 会报错"],ans:"B",exp:"BN和Dropout统计量可能不匹配。"},
{id:179,cat:"正则化",type:"choice",q:"Transformer中Dropout常用概率？",opts:["A. 0.5","B. 0.1","C. 0.3","D. 0.8"],ans:"B",exp:"CNN FC层用0.3~0.5。"},
{id:180,cat:"正则化",type:"choice",q:"L1正则效果？",opts:["A. 更均匀","B. 稀疏权重(部分=0)→特征选择","C. 权重更大","D. 无"],ans:"B",exp:"产生稀疏。"},
{id:181,cat:"正则化",type:"choice",q:"L2正则效果？",opts:["A. 稀疏","B. 限制权重大小→更平滑边界","C. 增权重","D. 删神经元"],ans:"B",exp:"λΣW²。"},
{id:182,cat:"正则化",type:"choice",q:"PyTorch中L2正则怎么设？",opts:["A. loss+L2","B. optimizer的weight_decay参数","C. model.l2","D. 无法设"],ans:"B",exp:"weight_decay就是L2系数。"},
{id:183,cat:"正则化",type:"choice",q:"数据增强为什么防过拟合？",opts:["A. 增参数","B. 随机变换迫使模型学习不变性特征","C. 减模型","D. 加快训练"],ans:"B",exp:"模型不记住无关细节。"},
{id:184,cat:"正则化",type:"truefalse",q:"数据增强测试时也需要。",ans:"false",exp:"只有训练时需要。"},
{id:185,cat:"正则化",type:"choice",q:"早停是什么？",opts:["A. 限时","B. 验证loss不降就停","C. 减epoch","D. 减batch"],ans:"B",exp:"监控验证集。"},
{id:186,cat:"正则化",type:"choice",q:"train_loss=0.05,val_loss=0.8什么情况？",opts:["A. 正常","B. 过拟合","C. 欠拟合","D. 数据不够"],ans:"B",exp:"训练好验证差=过拟合。"},
{id:187,cat:"正则化",type:"choice",q:"train_acc=55%,val_acc=53%什么情况？",opts:["A. 过拟合","B. 正常","C. 欠拟合","D. 数据太多"],ans:"C",exp:"都差=欠拟合。"},
{id:188,cat:"正则化",type:"choice",q:"过拟合解决不包括？",opts:["A. 加数据","B. Dropout","C. 增加深度","D. 早停"],ans:"C",exp:"增加深度加剧过拟合。"},
{id:189,cat:"正则化",type:"choice",q:"欠拟合解决？",opts:["A. 加Dropout","B. 增加模型容量","C. 早停","D. 减训练"],ans:"B",exp:"模型太弱需更强。"},
{id:190,cat:"正则化",type:"truefalse",q:"BatchNorm有轻微正则化效果。",ans:"true",exp:"mini-batch噪声有轻微正则。"},
{id:191,cat:"正则化",type:"choice",q:"Label Smoothing防止？",opts:["A. 梯度消失","B. 过度自信","C. 欠拟合","D. 数据不够"],ans:"B",exp:"预测概率不过分集中。"},
{id:192,cat:"正则化",type:"choice",q:"RandomHorizontalFlip提供？",opts:["A. 旋转不变","B. 左右翻转不变性","C. 缩放不变","D. 遮挡不变"],ans:"B",exp:"对物体左右翻转具有鲁棒性。"},
{id:193,cat:"正则化",type:"choice",q:"CutMix是什么？",opts:["A. 裁剪","B. 一图矩形区域粘贴到另一图","C. 混合标签","D. 随机擦除"],ans:"B",exp:"标签也按比例混合。"},
{id:194,cat:"正则化",type:"choice",q:"数据增强是正则化技术吗？",opts:["A. 不是","B. 是","C. 是优化","D. 不确定"],ans:"B",exp:"通过增加多样性防过拟合。"},
{id:195,cat:"正则化",type:"truefalse",q:"Dropout测试时需要手动缩放输出。",ans:"false",exp:"PyTorch自动处理。"},
// ===== 梯度问题 196-210 =====
{id:196,cat:"梯度问题",type:"choice",q:"梯度消失的现象？",opts:["A. loss飙升","B. loss下降极慢或停滞，浅层参数不更新","C. loss变NaN","D. loss震荡"],ans:"B",exp:"浅层梯度≈0→参数不更新。"},
{id:197,cat:"梯度问题",type:"choice",q:"梯度爆炸现象？",opts:["A. 缓慢下降","B. loss突然飙升或变NaN","C. 停滞","D. accuracy高"],ans:"B",exp:"参数更新过大→溢出。"},
{id:198,cat:"梯度问题",type:"choice",q:"解决梯度消失不包括？",opts:["A. ReLU","B. 增加网络深度","C. 残差连接","D. BatchNorm"],ans:"B",exp:"增加深度加剧消失。应该用ReLU/BN/残差/LSTM/Kaiming。"},
{id:199,cat:"梯度问题",type:"choice",q:"解决梯度爆炸首选？",opts:["A. 增加lr","B. 梯度裁剪clip_grad_norm_","C. 增加层数","D. 减batch"],ans:"B",exp:"直接限制梯度范数。"},
{id:200,cat:"梯度问题",type:"choice",q:"max_norm=5.0什么意思？",opts:["A. 梯度固定5","B. 梯度范数超5则按比例缩放","C. 删除超5的","D. lr=5"],ans:"B",exp:"只缩放不改变方向。"},
{id:201,cat:"梯度问题",type:"choice",q:"ResNet残差连接为什么缓解梯度消失？",opts:["A. 减参数","B. ∂H/∂x=∂F/∂x+1，+1保证梯度至少为1","C. 增lr","D. 用BN"],ans:"B",exp:"梯度高速通道。"},
{id:202,cat:"梯度问题",type:"choice",q:"Sigmoid导数最大值？",opts:["A. 1","B. 0.25","C. 0.5","D. 0"],ans:"B",exp:"σ'(x)=σ(x)(1-σ(x))最大0.25。"},
{id:203,cat:"梯度问题",type:"choice",q:"N层Sigmoid网络梯度约？",opts:["A. N","B. (0.25)^N→指数衰减趋近0","C. 0.25N","D. N²"],ans:"B",exp:"每层≤0.25连乘。"},
{id:204,cat:"梯度问题",type:"choice",q:"Kaiming初始化适用？",opts:["A. Sigmoid","B. ReLU系列","C. Softmax","D. Tanh"],ans:"B",exp:"方差2/fan_in补偿ReLU半输出置0。"},
{id:205,cat:"梯度问题",type:"choice",q:"Xavier初始化适用？",opts:["A. ReLU","B. Sigmoid/Tanh","C. GELU","D. Swish"],ans:"B",exp:"保持通过这些激活后方差稳定。"},
{id:206,cat:"梯度问题",type:"choice",q:"全零初始化问题？",opts:["A. 梯度爆炸","B. 所有神经元学相同特征(对称性)","C. 过拟合","D. 梯度消失"],ans:"B",exp:"等价于每层一个神经元。"},
{id:207,cat:"梯度问题",type:"choice",q:"Kaiming核心思想？",opts:["A. 权重更大","B. 方差2/fan_in补偿ReLU半输出置0","C. 权重更小","D. 固定权重"],ans:"B",exp:"保持信号方差稳定。"},
{id:208,cat:"梯度问题",type:"choice",q:"BN在batch=2时为什么差？",opts:["A. 太慢","B. 统计量噪声大(2样本不代表总体)","C. 不支持","D. 梯度爆炸"],ans:"B",exp:"训练和推理差异大。"},
{id:209,cat:"梯度问题",type:"choice",q:"梯度累积时loss为什么要除accumulation_steps？",opts:["A. 不用","B. 还原到平均loss否则scale变大lr语义改变","C. 加速","D. 防溢出"],ans:"B",exp:"4个小batch累积等价大batch，除以4还原。"},
{id:210,cat:"梯度问题",type:"truefalse",q:"梯度裁剪和降低lr可以同时使用。",ans:"true",exp:"两者原理不同可叠加。"},

// ===== 代码分析 211-240 =====
{id:211,cat:"代码分析",type:"choice",q:"看到nn.Conv2d→什么模型？",opts:["A. DNN","B. CNN","C. RNN","D. Transformer"],ans:"B",exp:"卷积层=CNN。"},
{id:212,cat:"代码分析",type:"choice",q:"看到nn.LSTM→什么模型？",opts:["A. CNN","B. RNN/LSTM","C. Transformer","D. MLP"],ans:"B",exp:"循环神经网络。"},
{id:213,cat:"代码分析",type:"choice",q:"看到nn.MultiheadAttention→什么模型？",opts:["A. RNN","B. CNN","C. Transformer","D. MLP"],ans:"C",exp:"Transformer核心组件。"},
{id:214,cat:"代码分析",type:"choice",q:"只有多层nn.Linear→什么模型？",opts:["A. CNN","B. DNN/MLP","C. RNN","D. Transformer"],ans:"B",exp:"全连接网络。"},
{id:215,cat:"代码分析",type:"choice",q:"nn.Embedding+nn.LSTM→什么模型？",opts:["A. 图像分类","B. 语言模型/文本生成","C. 目标检测","D. 分割"],ans:"B",exp:"词嵌入+序列处理=语言模型。"},
{id:216,cat:"代码分析",type:"choice",q:"看到CrossEntropyLoss→什么任务？",opts:["A. 回归","B. 多分类","C. 生成","D. 聚类"],ans:"B",exp:"多分类。"},
{id:217,cat:"代码分析",type:"choice",q:"看到MSELoss→什么任务？",opts:["A. 分类","B. 回归","C. 聚类","D. 生成"],ans:"B",exp:"回归。"},
{id:218,cat:"代码分析",type:"choice",q:"看到BCEWithLogitsLoss→什么任务？",opts:["A. 多分类","B. 二分类","C. 回归","D. 生成"],ans:"B",exp:"二分类。"},
{id:219,cat:"代码分析",type:"choice",q:"x.view(x.size(0),-1)做什么？",opts:["A. 复制","B. 展平：保持batch维，其余展平","C. 转置","D. 切片"],ans:"B",exp:"-1自动推断。"},
{id:220,cat:"代码分析",type:"choice",q:"transpose后直接view会？",opts:["A. 正常","B. 报错！需先.contiguous()","C. 结果错不报错","D. 加速"],ans:"B",exp:"transpose改变stride不连续。"},
{id:221,cat:"代码分析",type:"choice",q:"reshape和view区别？",opts:["A. 相同","B. reshape不需连续内存(更安全)","C. view更快","D. reshape不能改形状"],ans:"B",exp:"view需要连续内存。"},
{id:222,cat:"代码分析",type:"choice",q:"model.eval()和torch.no_grad()区别？",opts:["A. 相同","B. eval改模型行为(Dropout/BN)，no_grad关自动求导","C. eval更快","D. no_grad改模型行为"],ans:"B",exp:"推理时两者都用。"},
{id:223,cat:"代码分析",type:"choice",q:"x.shape=(2,3,224,224)，view(2,-1)中-1=？",opts:["A. 224","B. 672","C. 150528","D. 200704"],ans:"C",exp:"3×224×224=150528。"},
{id:224,cat:"代码分析",type:"choice",q:"torch.argmax(x,dim=1)做什么？",opts:["A. 找最大值","B. 沿dim=1找最大值索引","C. 排序","D. 取平均"],ans:"B",exp:"常用获取预测类别。"},
{id:225,cat:"代码分析",type:"choice",q:"squeeze做什么？",opts:["A. 加维度","B. 去掉大小为1的维度","C. 压缩","D. 排序"],ans:"B",exp:"(1,3,224,224)→(3,224,224)。"},
{id:226,cat:"代码分析",type:"choice",q:"unsqueeze做什么？",opts:["A. 去维度","B. 在指定位置插入大小为1的维度","C. 压缩","D. 展平"],ans:"B",exp:"(3,224,224)→unsqueeze(0)→(1,3,224,224)。"},
{id:227,cat:"代码分析",type:"choice",q:"permute做什么？",opts:["A. 展平","B. 多个维度重排","C. 裁剪","D. 填充"],ans:"B",exp:"(B,C,H,W)→permute(0,2,3,1)→(B,H,W,C)。"},
{id:228,cat:"代码分析",type:"choice",q:"x[x<0]=0相当于什么激活？",opts:["A. Sigmoid","B. ReLU","C. Tanh","D. Softmax"],ans:"B",exp:"max(0,x)=ReLU。"},
{id:229,cat:"代码分析",type:"choice",q:"Softmax中np.exp(x-np.max(x))为什么减max？",opts:["A. 加速","B. 防止e^x溢出","C. 减小","D. 归一化"],ans:"B",exp:"数值稳定技巧。"},
{id:230,cat:"代码分析",type:"choice",q:"LogSoftmax配合什么损失？",opts:["A. MSE","B. NLLLoss","C. BCE","D. CrossEntropy"],ans:"B",exp:"LogSoftmax+NLLLoss=CrossEntropyLoss。"},
{id:231,cat:"代码分析",type:"choice",q:"Linear(4096,10)含bias参数量？",opts:["A. 40960","B. 40970","C. 4096","D. 41000"],ans:"B",exp:"4096×10+10=40970。"},
{id:232,cat:"代码分析",type:"choice",q:"Embedding(5000,100)参数量？",opts:["A. 5000","B. 100","C. 500000","D. 50000"],ans:"C",exp:"5000×100=500K。"},
{id:233,cat:"代码分析",type:"choice",q:"BatchNorm(64)参数量？",opts:["A. 64","B. 128(γ和β各64)","C. 256","D. 0"],ans:"B",exp:"每个channel一对γ/β。"},
{id:234,cat:"代码分析",type:"choice",q:"LayerNorm(256)参数量？",opts:["A. 256","B. 512","C. 0","D. 1024"],ans:"B",exp:"γ+β各256。"},
{id:235,cat:"代码分析",type:"choice",q:"看到LogSoftmax+NLLLoss等价什么？",opts:["A. MSE","B. CrossEntropyLoss","C. BCE","D. MAE"],ans:"B",exp:"数值更稳定。"},
{id:236,cat:"代码分析",type:"choice",q:"隐藏层用Sigmoid问题？",opts:["A. 没啥","B. 梯度消失σ'≤0.25","C. 梯度爆炸","D. 过拟合"],ans:"B",exp:"应改ReLU。"},
{id:237,cat:"代码分析",type:"choice",q:"验证时不写eval()问题？",opts:["A. 没","B. Dropout仍丢弃，BN用batch统计非全局","C. 报错","D. 训练更慢"],ans:"B",exp:"eval()关闭Dropout、切换BN。"},
{id:238,cat:"代码分析",type:"choice",q:"验证时不写no_grad()问题？",opts:["A. 报错","B. 白白计算梯度浪费显存","C. 结果不对","D. 训练更慢"],ans:"B",exp:"不影响正确性但浪费。"},
{id:239,cat:"代码分析",type:"choice",q:"忘写zero_grad()问题？",opts:["A. 报错","B. 梯度累加","C. 没影响","D. 不训练"],ans:"B",exp:"除非有意梯度累积。"},
{id:240,cat:"代码分析",type:"choice",q:"F.softmax()后传F.cross_entropy()问题？",opts:["A. 正确","B. 双重Softmax→概率趋均→loss不降","C. 梯度爆炸","D. 过拟合"],ans:"B",exp:"CrossEntropyLoss内含LogSoftmax。"},
// ===== 对比学习与蒸馏 241-255 =====
{id:241,cat:"对比学习与蒸馏",type:"choice",q:"对比学习核心思想？",opts:["A. 监督学习","B. 拉近正样本对、推远负样本","C. 知识蒸馏","D. 过拟合"],ans:"B",exp:"自监督学通用表征。"},
{id:242,cat:"对比学习与蒸馏",type:"choice",q:"SimCLR正样本对怎么构造？",opts:["A. 不同图像同类","B. 同一张图的两个不同增强版本","C. 随机两张","D. 图和标签"],ans:"B",exp:"如不同裁剪/颜色变换。"},
{id:243,cat:"对比学习与蒸馏",type:"choice",q:"SimCLR负样本来自？",opts:["A. 手工标注","B. 同batch其他所有图","C. 随机生成","D. 数据库"],ans:"B",exp:"batch越大负样本越多。"},
{id:244,cat:"对比学习与蒸馏",type:"choice",q:"InfoNCE中τ的作用？",opts:["A. lr","B. 温度参数控制分布尖锐度","C. 衰减率","D. 动量"],ans:"B",exp:"通常0.07~0.1。"},
{id:245,cat:"对比学习与蒸馏",type:"choice",q:"SimCLR为什么需大batch？",opts:["A. 加速","B. 负样本来自batch，越大效果越好","C. GPU利用率","D. 增强需要"],ans:"B",exp:"原论文用batch=4096。"},
{id:246,cat:"对比学习与蒸馏",type:"choice",q:"SimCLR投影头训练完后？",opts:["A. 保留","B. 扔掉，只用Encoder做下游","C. 继续训","D. 微调"],ans:"B",exp:"Encoder保留更丰富语义。"},
{id:247,cat:"对比学习与蒸馏",type:"choice",q:"知识蒸馏核心？",opts:["A. 自学","B. 大模型(教师)教小模型(学生)","C. 数据增强","D. 过拟合"],ans:"B",exp:"模型压缩。"},
{id:248,cat:"对比学习与蒸馏",type:"choice",q:"软标签比硬标签多了什么？",opts:["A. 准确率","B. 类间相似性信息","C. 梯度","D. 没区别"],ans:"B",exp:"如7像1、猫像狗。"},
{id:249,cat:"对比学习与蒸馏",type:"choice",q:"蒸馏温度τ>1的作用？",opts:["A. 加速","B. 软化分布让学生看到细粒度类间关系","C. 正则","D. 增强"],ans:"B",exp:"非目标类信息更明显。"},
{id:250,cat:"对比学习与蒸馏",type:"choice",q:"对比学习和蒸馏核心区别？",opts:["A. 都监督","B. 对比无标签自学通用表征；蒸馏有教师压缩模型","C. 都无监督","D. 没区别"],ans:"B",exp:"自监督vs有教师监督。"},
{id:251,cat:"对比学习与蒸馏",type:"choice",q:"CLIP是什么？",opts:["A. 图像分割","B. 跨模态对比(图-文匹配)","C. 语音识别","D. 翻译"],ans:"B",exp:"正样本=图+文描述。"},
{id:252,cat:"对比学习与蒸馏",type:"choice",q:"跨模态蒸馏.detach()作用？",opts:["A. 加速","B. 防止梯度流向教师(只更新学生)","C. 正则","D. 增强"],ans:"B",exp:"教师不被学生带偏。"},
{id:253,cat:"对比学习与蒸馏",type:"choice",q:"知识蒸馏三种形式？",opts:["A. 预训练/微调/推理","B. Logit级/特征级/关系级","C. 监督/无监督/半监督","D. CNN/RNN/Transformer"],ans:"B",exp:"模仿输出/中间层/样本间关系。"},
{id:254,cat:"对比学习与蒸馏",type:"choice",q:"教师通常比学生大很多为什么？",opts:["A. GPU支持","B. 教师大→特征更丰富→蒸馏信息量大","C. 训练快","D. 没原因"],ans:"B",exp:"大教师软标签信息量大。"},
{id:255,cat:"对比学习与蒸馏",type:"choice",q:"SimCLR原论文用多大batch？",opts:["A. 32","B. 256","C. 4096","D. 64"],ans:"C",exp:"需要大量负样本。"},

// ===== 激活函数 256-270 =====
{id:256,cat:"激活函数",type:"choice",q:"ReLU公式？",opts:["A. 1/(1+e^(-x))","B. max(0,x)","C. tanh(x)","D. e^x/Σe^x"],ans:"B",exp:"正区间=x，负区间=0。"},
{id:257,cat:"激活函数",type:"choice",q:"ReLU输出范围？",opts:["A. (0,1)","B. [0,+∞)","C. (-1,1)","D. (-∞,+∞)"],ans:"B",exp:"负区间为0。"},
{id:258,cat:"激活函数",type:"choice",q:"ReLU主要缺点？",opts:["A. 计算复杂","B. Dead ReLU","C. 梯度消失","D. 梯度爆炸"],ans:"B",exp:"负区间梯度=0。"},
{id:259,cat:"激活函数",type:"choice",q:"Dead ReLU是什么？",opts:["A. 模型崩溃","B. 神经元始终输出0，梯度永远0，权重永不更新","C. 梯度消失","D. 过拟合"],ans:"B",exp:"输入始终<0→永久失活。"},
{id:260,cat:"激活函数",type:"choice",q:"LeakyReLU怎么解决Dead ReLU？",opts:["A. 增大lr","B. 负区间有小斜率0.01","C. 用BN","D. 减小网络"],ans:"B",exp:"保证负区间有梯度。"},
{id:261,cat:"激活函数",type:"choice",q:"Sigmoid输出范围？",opts:["A. (-1,1)","B. (0,1)","C. [0,+∞)","D. (-∞,+∞)"],ans:"B",exp:"概率解释。"},
{id:262,cat:"激活函数",type:"choice",q:"Tanh输出范围？",opts:["A. (0,1)","B. (-1,1)","C. [0,+∞)","D. (-∞,+∞)"],ans:"B",exp:"零均值。"},
{id:263,cat:"激活函数",type:"choice",q:"Sigmoid导数最大值？",opts:["A. 1","B. 0.25","C. 0.5","D. 0"],ans:"B",exp:"σ'(x)=σ(x)(1-σ(x))最大0.25。"},
{id:264,cat:"激活函数",type:"choice",q:"为什么Sigmoid导致梯度消失？",opts:["A. 不可导","B. 导数≤0.25，N层连乘→(0.25)^N→0","C. 值域小","D. 太慢"],ans:"B",exp:"指数衰减。"},
{id:265,cat:"激活函数",type:"choice",q:"GELU是什么模型首选？",opts:["A. CNN","B. Transformer","C. RNN","D. GAN"],ans:"B",exp:"BERT、GPT默认激活。"},
{id:266,cat:"激活函数",type:"choice",q:"Softmax用于？",opts:["A. 隐藏层","B. 多分类输出层","C. 输入层","D. 池化层"],ans:"B",exp:"转为概率分布。"},
{id:267,cat:"激活函数",type:"choice",q:"没有激活函数多层网络等价？",opts:["A. 更深","B. 单层线性变换","C. CNN","D. RNN"],ans:"B",exp:"W₂(W₁x)=(W₂W₁)x。"},
{id:268,cat:"激活函数",type:"choice",q:"隐藏层最常用激活？",opts:["A. Sigmoid","B. ReLU","C. Softmax","D. Tanh"],ans:"B",exp:"默认首选。"},
{id:269,cat:"激活函数",type:"choice",q:"二分类输出层用？",opts:["A. ReLU","B. Sigmoid","C. Softmax","D. Tanh"],ans:"B",exp:"输出0~1概率。"},
{id:270,cat:"激活函数",type:"choice",q:"回归输出层用？",opts:["A. Sigmoid","B. Softmax","C. ReLU","D. 无激活"],ans:"D",exp:"需任意实数值。"},

// ===== 多模态 271-280 =====
{id:271,cat:"多模态",type:"choice",q:"多模态融合常见策略？",opts:["A. 只用拼接","B. 拼接/加权求和/Cross-Attention/门控融合","C. 只用融合","D. 只用Cross-Attn"],ans:"B",exp:"多种策略可选。"},
{id:272,cat:"多模态",type:"choice",q:"拼接和Cross-Attention本质区别？",opts:["A. 计算量","B. 拼接静态无交互；Cross-Attention有动态信息交互","C. 参数量","D. 没区别"],ans:"B",exp:"Cross-Attn有选择性关注。"},
{id:273,cat:"多模态",type:"choice",q:"为什么文本通常比音频/图像准确？",opts:["A. 文本更多","B. 文本是离散符号语义明确，音频/图像连续信号语义模糊","C. 模型大","D. 没区别"],ans:"B",exp:"'我很生气'比从语调推断更可靠。"},
{id:274,cat:"多模态",type:"choice",q:"ELACL锚点用什么生成？",opts:["A. 随机","B. 预训练语言模型","C. 手工","D. 聚类"],ans:"B",exp:"如RoBERTa编码情感词汇。"},
{id:275,cat:"多模态",type:"choice",q:"锚点为什么不用随机初始化？",opts:["A. 无法训练","B. 预训练模型有语义先验，收敛更快","C. 随机更大","D. 不确定"],ans:"B",exp:"'happy'和'sad'自然分离。"},
{id:276,cat:"多模态",type:"choice",q:"Cross-Attention融合中'双向'指？",opts:["A. 前向反向","B. 文本看音频+音频看文本","C. 训练推理","D. 编码解码"],ans:"B",exp:"双向信息交互。"},
{id:277,cat:"多模态",type:"choice",q:"门控融合的门可能退化吗？",opts:["A. 不会","B. 可能退化为只信任一种模态","C. 必须退化","D. 不确定"],ans:"B",exp:"门=0或1时融合失效。"},
{id:278,cat:"多模态",type:"choice",q:"多模态对齐用什么数据？",opts:["A. 随机","B. 配对数据(如同时有文本和音频的同段对话)","C. 无标签","D. 合成"],ans:"B",exp:"配对提供跨模态对齐信号。"},
{id:279,cat:"多模态",type:"choice",q:"CLIP是什么？",opts:["A. 分割","B. 跨模态对比(图文匹配)","C. 语音识别","D. 翻译"],ans:"B",exp:"零样本图像分类。"},
{id:280,cat:"多模态",type:"truefalse",q:"知识蒸馏可以跨模态使用，如文本模型教音频模型。",ans:"true",exp:"配对数据+文本特征更干净可做指导。"},

// ===== 综合与进阶 281-300 =====
{id:281,cat:"综合与进阶",type:"choice",q:"图像分类小数据(500张)用什么模型？",opts:["A. 从头训练ViT","B. 预训练ResNet+替换分类头+微调","C. 从头训CNN","D. DNN"],ans:"B",exp:"迁移学习小数据最佳。"},
{id:282,cat:"综合与进阶",type:"choice",q:"文本分类用什么？",opts:["A. GPT","B. BERT/RoBERTa(Encoder-Only)","C. CNN","D. LSTM"],ans:"B",exp:"理解任务用双向注意力。"},
{id:283,cat:"综合与进阶",type:"choice",q:"文本生成用什么？",opts:["A. BERT","B. GPT/LLaMA(Decoder-Only)","C. CNN","D. SVM"],ans:"B",exp:"自回归生成。"},
{id:284,cat:"综合与进阶",type:"choice",q:"机器翻译用什么架构？",opts:["A. Encoder-Only","B. Decoder-Only","C. Encoder-Decoder(T5)","D. CNN"],ans:"C",exp:"编码源语言+解码目标语言。"},
{id:285,cat:"综合与进阶",type:"choice",q:"1000条时序数据用LSTM还是Transformer？",opts:["A. Transformer","B. LSTM(数据少，Transformer需大量数据)","C. CNN","D. SVM"],ans:"B",exp:"LSTM参数少小数据友好。"},
{id:286,cat:"综合与进阶",type:"choice",q:"目标检测用什么？",opts:["A. BERT","B. YOLO/Faster R-CNN","C. GPT","D. LSTM"],ans:"B",exp:"YOLO快，Faster R-CNN准。"},
{id:287,cat:"综合与进阶",type:"choice",q:"语义分割用什么？",opts:["A. GPT","B. U-Net/DeepLab","C. ResNet","D. BERT"],ans:"B",exp:"Encoder-Decoder+跳跃连接适合像素级。"},
{id:288,cat:"综合与进阶",type:"choice",q:"500张图2分类怎么选？",opts:["A. 从头大模型","B. 预训练ResNet18+替换FC+微调","C. 随机","D. KNN"],ans:"B",exp:"迁移学习。"},
{id:289,cat:"综合与进阶",type:"choice",q:"batch_size=2时BN应换成？",opts:["A. 继续BN","B. LayerNorm或GroupNorm","C. 不用归一化","D. InstanceNorm"],ans:"B",exp:"BN小batch统计量不稳定。"},
{id:290,cat:"综合与进阶",type:"choice",q:"Precision公式？",opts:["A. TP/(TP+FN)","B. TP/(TP+FP)","C. 2PR/(P+R)","D. TP/(TP+TN)"],ans:"B",exp:"预测为正的中有多少是真的。"},
{id:291,cat:"综合与进阶",type:"choice",q:"Recall公式？",opts:["A. TP/(TP+FP)","B. TP/(TP+FN)","C. TN/(TN+FP)","D. 2PR/(P+R)"],ans:"B",exp:"所有正样本被找出多少。"},
{id:292,cat:"综合与进阶",type:"choice",q:"F1 score公式？",opts:["A. P+R","B. 2PR/(P+R)","C. P×R","D. (P+R)/2"],ans:"B",exp:"精确率和召回率的调和平均。"},
{id:293,cat:"综合与进阶",type:"choice",q:"什么情况下准确率高但F1低？",opts:["A. 数据多","B. 类别严重不均衡","C. 模型太好","D. 数据少"],ans:"B",exp:"如990猫10狗全预测为猫准确率99%但狗F1=0。"},
{id:294,cat:"综合与进阶",type:"choice",q:"混淆矩阵做什么？",opts:["A. 训练","B. 可视化每类预测正确/错误情况","C. 增强","D. 调参"],ans:"B",exp:"发现模型偏好。"},
{id:295,cat:"综合与进阶",type:"choice",q:"AUC-ROC适用？",opts:["A. 多分类","B. 二分类排序质量评估","C. 回归","D. 聚类"],ans:"B",exp:"区分正负样本的排序能力。"},
{id:296,cat:"综合与进阶",type:"choice",q:"SwiGLU是什么？",opts:["A. CNN","B. 门控FFN，LLM首选","C. 优化器","D. 损失"],ans:"B",exp:"LLaMA等现代LLM用于替代ReLU FFN。"},
{id:297,cat:"综合与进阶",type:"choice",q:"RoPE是什么？",opts:["A. 正则化","B. 旋转位置编码，LLaMA/Qwen使用","C. 优化器","D. 损失"],ans:"B",exp:"支持长上下文外推。"},
{id:298,cat:"综合与进阶",type:"choice",q:"Sparse Attention做什么？",opts:["A. 增加计算","B. 只算部分位置注意力降低O(L²)复杂度","C. 数据增强","D. 正则"],ans:"B",exp:"处理长序列。"},
{id:299,cat:"综合与进阶",type:"choice",q:"LLaMA用什么位置编码？",opts:["A. 正弦","B. RoPE(旋转位置编码)","C. 可学习","D. 不用"],ans:"B",exp:"支持长上下文外推。"},
{id:300,cat:"综合与进阶",type:"choice",q:"最适合长文本理解的模型？",opts:["A. DNN","B. CNN","C. RNN","D. Transformer"],ans:"D",exp:"Self-Attention直接建模任意位置依赖，长距离能力最强。"}
];

// 分类列表
const categories = [...new Set(questionBank.map(q => q.cat))];